[custom]
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/rules/LocalAreaNetwork.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/buding1987/pbyun/main/MoreDirect.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/AddAD.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/rules/Microsoft.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/rules/Apple.list
ruleset=📺 油管Tube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 NBC节点,https://raw.githubusercontent.com/buding1987/pbyun/main/NBCMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/ProgramProxy.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/buding1987/pbyun/refs/heads/main/rules/ProxyLite.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🌍 国外媒体`select`[]♻️ 自动选择`.*
custom_proxy_group=📺 油管Tube`select`[]🌍 国外媒体`(日本|东京|JP|Japan)`(US|HBO|美国)`[]🇺🇲 美国节点
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT`[]🎥 NBC节点
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🎥 NBC节点
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]REJECT`[]🌍 国外媒体`[]🎥 NBC节点
custom_proxy_group=🎥 NBC节点`select`[]🇺🇲 美国节点`(US|HBO|美国)`[]🌍 国外媒体
custom_proxy_group=🇺🇲 美国节点`url-test`(US|HBO|美国)
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,,50

enable_rule_generator=true
overwrite_original_rules=true
